// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwpFRGLRIVRwg5HWY6_uCzPxPwU72SkHg',
    appId: '1:459623171333:web:b7f3d3ccbcdc2c3a75236c',
    messagingSenderId: '459623171333',
    projectId: 'test-todo-6056e',
    authDomain: 'test-todo-6056e.firebaseapp.com',
    databaseURL: 'https://test-todo-6056e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-todo-6056e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFinqP0FOK0Ad-ERwdQbUYBSK2mAhlqps',
    appId: '1:459623171333:android:08f44ecf7839e92a75236c',
    messagingSenderId: '459623171333',
    projectId: 'test-todo-6056e',
    databaseURL: 'https://test-todo-6056e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-todo-6056e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqV2Z0W1TqlYivUaAskLC3AkszQv40yko',
    appId: '1:459623171333:ios:0d3a9307a52a374675236c',
    messagingSenderId: '459623171333',
    projectId: 'test-todo-6056e',
    databaseURL: 'https://test-todo-6056e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-todo-6056e.appspot.com',
    iosClientId: '459623171333-ao9on7d7ftlg8p1k5pugvck3uefjng5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.lotto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqV2Z0W1TqlYivUaAskLC3AkszQv40yko',
    appId: '1:459623171333:ios:0d3a9307a52a374675236c',
    messagingSenderId: '459623171333',
    projectId: 'test-todo-6056e',
    databaseURL: 'https://test-todo-6056e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-todo-6056e.appspot.com',
    iosClientId: '459623171333-ao9on7d7ftlg8p1k5pugvck3uefjng5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.lotto',
  );
}
